### ISSUE TITLE
ERROR - NOK login. Error in parsing /signing request

### ISSUE THREAD

**Issue by PatrikPatrik2** [PierreLevres/BlUVO#2]
Biuvo has worked perfectly since I installed it, but since a few days I start geting error messages and can no longer enter

ERROR - NOK login. Error in parsing /signing request

Why is that?

**Comment by PierreLevres** [comment]
logout and login from your phone app please.
typically these errors occur when a password or pin change is needed, or tha Kia wants you to change your account to the new generic Kia accounts.

**Comment by PatrikPatrik2** [comment]
When I logged in again in the phone app, then the app forced me to create a KIA account, and use that as a log in. Using the updated password and id (on the KIA accunt) I still can not get in, but the error code changed somewhat:

NOK login. Error: 400

**Comment by PierreLevres** [comment]
Is the password you used for the new account the same as for the old account? In the bluelinky discord channel several people struggled with the new accounts and what to use in the app and what to use in bluelinky/kuvork. For me both email addresses and passwords are identical.

**Comment by PatrikPatrik2** [comment]
I did as you said and used the same id and pw on both accounts, and now it works!!! Thanks you ever so much for your support, very much appreciated!!!
