### ISSUE TITLE
NOK deviceID. Error: 401

### ISSUE THREAD

**Issue by PatrikPatrik2** [PierreLevres/BlUVO#3]
Hi,

BIUVO has worked great, but since some time it does no longer work and I get this error code:
NOK deviceID. Error: 401

What's wrong?

**Comment by PierreLevres** [comment]
Kia and Hyundai changed the API interface. There is a new version in test: 6.1.0-alpha4. You should enter brand = ‘K’ in your config file for Kia.

**Comment by PatrikPatrik2** [comment]
I found  car_brand = "kia" in bluvo_main, should that be replaced with car_brand = "K"?

**Comment by PierreLevres** [comment]
Really sorry, thought the mail came from the Kuvork git, so i gave the wrong answer. Bluvo isnt ready yet for the new way of authentication by Kia and Kyundai. Struggling with the console menu as the upgrade to python 3.9 messed it up.
Probably a release later this week. Brand is not necessary, it determines it from the parameter p_abrp_carmodel = 'kia:niro:19:64:other'

**Comment by PierreLevres** [comment]
Fixed in new release
