### ISSUE TITLE
NOK deviceID. Error: 401{"retCode":"F","resCode":"4017","resMsg":"Invalid request value - Invalid Application Id.","msgId":"dbceef95-2615-461f-8451-2848dc236510"}

### ISSUE THREAD

**Issue by PatrikPatrik2** [PierreLevres/BlUVO#4]
I could not get the new version to run.

I used the same params.py that worked in the previous version.

I did not understand where to update the car_brand, so I hard coded it into line 167 of bluvio_lib.py
get_constants('kia')

When I did this it run, but I get this error message
NOK deviceID. Error: 401{"retCode":"F","resCode":"4017","resMsg":"Invalid request value - Invalid Application Id.","msgId":"dbceef95-2615-461f-8451-2848dc236510"}

**Comment by gracar2002** [comment]
There's a new line in the readme. Solved my similar (but not identical) issue.

`If running from Domoticz, be sure to move kialist.txt and hyundailist.txt into your domoticz homefolder.`

**Comment by PierreLevres** [comment]
What are you running from? Stand alone or from Domoticz? What if you run in debug mode? Having the *list.txt files in your working directory is essential.

**Comment by PatrikPatrik2** [comment]
i run it stand alone (bluvo.py). The *list.txt files are in the directory from which I run bluvo.py. How do I run in debug?

**Comment by PierreLevres** [comment]
The error you see is probably related to an invalid stamp. There was an error in the bluvo_lib in saving and reading that stamp from the pickle file. I submitted a new one.
Please remove session.pkl and update bluvo_lib.py and try again.
Please exit then and try a second run. 
If you then still have an error please check bluvo.log. You run it stand alone, so debug is automatically enabled. In your bluvo.log you will see

2021-03-05 12:53:33,300 - root - INFO - entering login <brand> <user-name>
2021-03-05 12:53:33,329 - root - DEBUG - constants <cssp app id> Basic <token> < 

I am interested in those two lines: is the correct brand set and doest it return a correct stamp.

**Comment by PatrikPatrik2** [comment]
It works! Thanks!!!!!!!!

**Comment by PierreLevres** [comment]
Development and maintenance stopped. Feel free to fork and adjust the code yourself.
