### ISSUE TITLE
Sometime HV state of charge = 0%

### ISSUE THREAD

**Issue by CreasolTech** [PierreLevres/BlUVO#5]
Hi. 
First, thanks a lot for your very good plugin! I'm happy to control my Kia eNiro by Domoticz!
I put the following control on plugin.py at line 212 to avoid that sometimes battery charge is set to 0%:

                    if (parsedStatus['chargeHV']>0):    #avoid to set soc=0% 
                        UpdateDevice(4, parsedStatus['chargeHV'], parsedStatus['chargeHV'])  # soc 

Regards.
Paolo

**Comment by PierreLevres** [comment]
Glad you like it. I am currently rebuilding it since the login sequence is changing. Will implement  your suggestion.

**Comment by PierreLevres** [comment]
Development and maintenance stopped. Feel free to fork and adjust the code yourself.
