### ISSUE TITLE
FlagInCar in domoticz?

### ISSUE THREAD

**Issue by mvroosmalen1970** [PierreLevres/BlUVO#7]
Hi,

Does this mean I need to create a dummy switch FlagInCar?
>>>
Watching the domoticz "FlagInCar"-devices. Car will be polled if that flag is set to 1. Flag will be turned off, once the data is read from the car. If you use iOS you can achieve enabling and disabling this flag by iOS Shortcuts when plugin in and out of Apple Carplay.

Or should this be created on first run of the plug in. The device is not create, so assume I need to create a dummy switch. Can you confirm?

Mark

**Comment by PierreLevres** [comment]
Yes you need to create a dummy switch.
